# Generated by Django 3.1.7 on 2022-09-30 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('build_status', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('construction_type', models.IntegerField(blank=True, null=True)),
                ('date_diff', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_in', models.DateTimeField(blank=True, null=True)),
                ('property_type', models.PositiveSmallIntegerField(choices=[(0, 'property type 0'), (1, 'property type 1'), (2, 'property type 2'), (3, 'property type 3'), (4, 'property type 4')], default=1)),
                ('end_week', models.IntegerField(blank=True, null=True)),
                ('typology_type', models.IntegerField(blank=True, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('boundary_id', models.IntegerField(blank=True, null=True)),
                ('id_uda', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('listing_type', models.IntegerField(blank=True, null=True)),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('start_week', models.IntegerField(blank=True, null=True)),
                ('end_quarter', models.IntegerField(blank=True, null=True)),
                ('last_activity', models.IntegerField(blank=True, null=True)),
                ('start_quarter', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'unique_together': {('id_uda', 'title')},
            },
        ),
    ]
